name: movietube
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.5
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.1.2
  path: ^1.9.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  uuid: ^4.5.1
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.5
  provider: ^6.1.4
  firebase_core: ^3.12.1
  image: ^4.5.2
  archive: ^4.0.5
  grpc: ^4.0.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
