// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxR3HHVKukggj8y6dskfssMCyPcxR9JF0',
    appId: '1:581634504628:web:7bcdad8815e6aa38d9a4e1',
    messagingSenderId: '581634504628',
    projectId: 'movietube-b2474',
    authDomain: 'movietube-b2474.firebaseapp.com',
    databaseURL: 'https://movietube-b2474-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movietube-b2474.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfeMpJfsyCg-mxm7ixOqKMz6qRbCti7TM',
    appId: '1:581634504628:android:fbb74da9ee0a7247d9a4e1',
    messagingSenderId: '581634504628',
    projectId: 'movietube-b2474',
    databaseURL: 'https://movietube-b2474-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movietube-b2474.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMRb-o5Z8GF9S1RY1miVzTBS1145zd7kE',
    appId: '1:581634504628:ios:6cb57158851bb987d9a4e1',
    messagingSenderId: '581634504628',
    projectId: 'movietube-b2474',
    databaseURL: 'https://movietube-b2474-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movietube-b2474.firebasestorage.app',
    iosClientId: '581634504628-421h0kn8o21rnt4rq5urhfm5v37dv310.apps.googleusercontent.com',
    iosBundleId: 'com.example.movietube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMRb-o5Z8GF9S1RY1miVzTBS1145zd7kE',
    appId: '1:581634504628:ios:6cb57158851bb987d9a4e1',
    messagingSenderId: '581634504628',
    projectId: 'movietube-b2474',
    databaseURL: 'https://movietube-b2474-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movietube-b2474.firebasestorage.app',
    iosClientId: '581634504628-421h0kn8o21rnt4rq5urhfm5v37dv310.apps.googleusercontent.com',
    iosBundleId: 'com.example.movietube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxR3HHVKukggj8y6dskfssMCyPcxR9JF0',
    appId: '1:581634504628:web:e9fe84d31fb27fa8d9a4e1',
    messagingSenderId: '581634504628',
    projectId: 'movietube-b2474',
    authDomain: 'movietube-b2474.firebaseapp.com',
    databaseURL: 'https://movietube-b2474-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'movietube-b2474.firebasestorage.app',
  );

}